pool:
  vmImage: 'ubuntu-latest'

schedules:
  - cron: "* */6 * * *"
    branches:
      include:
        - master

steps:
- script: |
    bash <(curl https://nixos.org/nix/install)
    source ~/.nix-profile/etc/profile.d/nix.sh
    nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
    nix-channel --update
    mkdir -p $HOME/.config/nix
    nix-env -iA cachix -f https://cachix.org/api/v1/install
    cachix use shyim
   
  displayName: 'Setup Nix Package Manager'

- script: |
    source ~/.nix-profile/etc/profile.d/nix.sh
    nix-build ci.nix -A buildOutputs

  displayName: 'Build'

- script: |
    source ~/.nix-profile/etc/profile.d/nix.sh
    nix eval -f default.nix 'lib'
    nix eval -f default.nix 'modules'
    nix eval -f default.nix 'overlays'

  displayName: 'Test nix code'

- script: |
    source ~/.nix-profile/etc/profile.d/nix.sh
    nix-build ci.nix -A cacheOutputs | cachix push

  displayName: 'Upload to Cache'
