name: CI
on:
  push:
  schedule:
    - cron: '0 3 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: shyim
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          
      - name: Build
        run: nix-build ci.nix -A buildOutputs
      
      - name: Upload Cache
        run: nix-build ci.nix -A cacheOutputs | cachix push shyim
